<a href="https://colab.research.google.com/github/Gcarmnonapy7/FIAP-Aurora-Siger/blob/main/Aurora_siger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Temperatura interna e externa;
Integridade estrutural (0/1);
Níveis de energia (%);
Pressão dos tanques;
Status dos módulos críticos.

DATA LOADING & CLEANING -> EDA -> FEATURE ENGINEERING -> DATA SPLITTING (TRAIN/VALIDATION/TEST) -> TRAINING MODEL -> MODEL VALIDATION -> HYPERPARAMETERS -> SAVE THE ARTEFACT

In [1]:
# === import libraries ===

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest

In [6]:
sns.set_style('darkgrid')
np.random.seed(42)
n_samples = 1000_000
anomalie_ratio = 0.03
n_anomalies = int(n_samples * anomalie_ratio)

In [18]:
normal_data = pd.DataFrame({
    'temperatura_interna': np.random.normal(loc=22,scale=2,size=n_samples - n_anomalies),
    'temperatura_externa'  : np.random.normal(loc=15,scale=10,size=n_samples - n_anomalies),
    'integridade_estrutural' : np.random.choice([0,1],size=n_samples - n_anomalies,p=[anomalie_ratio,0.97]),
    'energy' : np.random.normal(loc=95,scale=3,size=n_samples - n_anomalies),
    'vibration' : np.random.normal(loc=0.2,scale=0.5,size=n_samples - n_anomalies),
})

# external_temp affects the infra

In [19]:
normal_data.head()

   temperatura_interna  temperatura_externa  ...     energy  vibration
0            20.849365            15.361629  ...  93.134874   0.272862
1            26.321176            27.629837  ...  98.117889   0.874002
2            22.393192            11.968645  ...  93.581815  -0.406338
3            25.042010            -1.745512  ...  94.228000   0.410833
4            25.073899            23.117592  ...  94.763147   0.253620

[5 rows x 5 columns]

In [20]:
normal_data.describe()

       temperatura_interna  temperatura_externa  ...         energy      vibration
count        970000.000000        970000.000000  ...  970000.000000  970000.000000
mean             21.999516            15.004365  ...      94.996208       0.199385
std               2.002056            10.003830  ...       3.004101       0.500393
min              11.821506           -32.363317  ...      80.599674      -2.293366
25%              20.650687             8.262605  ...      92.963975      -0.137390
50%              21.997912            14.996470  ...      94.992374       0.199208
75%              23.351440            21.742830  ...      97.022949       0.537198
max              32.057296            65.646046  ...     108.975959       2.576910

[8 rows x 5 columns]